name: Action-workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input version'
        default: 'latest'
        required: true
jobs:
  prepare:
    runs-on: self-hosted
    steps: 
      - name: Set tag on workflow despatch
        if: github.even_name == 'workflow_dispatch'
        run: echo "${{ github.even.inputs.version }}"

  build: 
    needs: prepare
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker login
        run:  docker login -u supawitchinpa -p ${{ secrets.DECKER_PASS }}
      - name: build and push
        run: |
          cd action-lab/Docker
          docker build -t supawitchinpa/labgithub:${{ github.event.inputs.version }} .
          docker push supawitchinpa/labgithub:${{ github.event.inputs.version }}
  Deploy: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: deploy container 
        run:  docker run -d -p 8083:80 supawitchinpa/labgithub:${{ github.event.inputs.version }}